version: '3.8'

services:
  nuxt:
    container_name: witch-it.space--nuxt
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    deploy:
        resources:
            limits:
                cpus: 4
                memory: 8000M

  postgres:
    container_name: witch-it.space--postgres
    image: postgres:10-alpine
    volumes:
      - /media/witchit-space/db:/var/lib/postgresql/data:z
    env_file: .env
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: witch-it.space--nginx
    links:
      - nuxt
    ports:
      - 81:80
      - 444:443
